### ISSUE TITLE
how to specify python version and requirements.txt

### ISSUE THREAD

**Issue by harrywang** [my8100/scrapydweb#87]
Thanks for working on this great project. I have followed your instructions to setup scrapyd and scrapydweb on heroku, but ran into issue that there are other package dependencies in my scrapy project such as sqlalchemy. 

When I deploy to scrapinghub.com, I specify that in the scrapinghub.yml in my project as follows:
```yml
project: 404937

stacks:
    default: scrapy:1.7-py3
requirements:
  file: requirements.txt
```

How to do this for Scrapydweb?

Thanks a lot!
